# ===== SERVER =====
server.port=8080

# ===== APPLICATION =====
spring.application.name=home-accounting

# ===== DATABASE =====
spring.datasource.url=jdbc:postgresql://localhost:5432/home_accounting
spring.datasource.username=postgres
spring.datasource.password=Ss@z26041960
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== FLYWAY =====
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# ===== JWT =====
jwt.secret=home-accounting-secret-key-for-jwt-token-signing-2024
jwt.expiration=86400000